# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0002_remove_book_rating'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorited_books',
            field=models.ManyToManyField(to='user_page.Book'),
        ),
    ]
